ifndef REACTOR_PLATFORM
REACTOR_PLATFORM = 1
PLATFORM_OBJ_DIR = $(OBJ_DIR)/platform

BOARD_DIR    = $(PLATFORM_DIR)/board/$(BOARD_VENDOR)/$(BOARD)
CHIP_DIR     = $(PLATFORM_DIR)/chip/$(CHIP_VENDOR)/$(CHIP)
CORE_DIR     = $(PLATFORM_DIR)/core/$(CORE_VENDOR)/$(CORE_ARCH)
KERNEL_DIR   = $(PLATFORM_DIR)/kernel/$(KERNEL)/$(KERNEL_VERSION)

BOARD_OBJ_DIR  = $(PLATFORM_OBJ_DIR)/board
CHIP_OBJ_DIR   = $(PLATFORM_OBJ_DIR)/chip
CORE_OBJ_DIR   = $(PLATFORM_OBJ_DIR)/core
KERNEL_OBJ_DIR = $(PLATFORM_OBJ_DIR)/kernel

include $(BOARD_DIR)/board.mk
include $(CHIP_DIR)/chip.mk
include $(CORE_DIR)/core.mk
include $(KERNEL_DIR)/kernel.mk

PLATFORM_STRING=$(CORE_ID)_$(KERNEL)_$(BOARD)

PLATFORM_LIB_NAME=rpi-backend_$(PLATFORM_STRING)

PLATFORM_LIBFLAGS=-l$(PLATFORM_LIB_NAME)

PLATFORM_LIB=$(DISTDIR)/lib$(PLATFORM_LIB_NAME).a

PLATFORM_INCLUDES=-I$(PLATFORM_DIR) -I$(BOARD_DIR) -I$(CHIP_DIR) -I$(CORE_DIR) \
-I$(KERNEL_DIR) $(CORE_INCLUDES) $(CHIP_INCLUDES) $(BOARD_INCLUDES) $(KERNEL_INCLUDES)

PLATFORM_OBJECTS=$(CORE_OBJECTS) $(CHIP_OBJECTS) $(BOARD_OBJECTS) $(KERNEL_OBJECTS)

PLATFORM_FLAGS=$(CORE_FLAGS) $(CHIP_FLAGS) $(BOARD_FLAGS) $(KERNEL_FLAGS)

ifneq ($(NAME), rpi-backend)
$(PLATFORM_LIB):
	$(MAKE) -C $(PLATFORM_DIR)
endif

endif
